### ISSUE TITLE
Some query methods don't accept query objects as arguments

### ISSUE THREAD

**Issue by james-whiteside** [vaticle/typedb-driver#420]
## Description

The `TypeDBQuery.matchAggregate`, `.matchGroup`, and `.matchGroupAggregate` do not accept `TypeQLQuery` objects as arguments, only strings. This is inconsistent with the other `TypeDBQuery` methods that accept either an object or a string as the argument.

## Environment

1. Ubuntu 22.04.2 LTS
2. TypeDB version 2.17.0

## Expected Output

`TypeQLQuery` objects are accepted as arguments for all `TypeDBQuery` methods. 

## Actual Output

This is not the case for some methods.
 
## Additional information

![](https://cdn.discordapp.com/attachments/983799734697336892/1110886663024037918/Screenshot_2023-05-24_at_12.06.38.png)

**Comment by flyingsilverfin** [comment]
This is not true as of 2.24.x for sure, but likely also fixed earlier.
