### ISSUE TITLE
Rust Chrono versions conflict

### ISSUE THREAD

**Issue by STPR** [vaticle/typedb-driver#665]
Hello,
I'm following the documentation to install the Rust driver and I've a conflict error:
```error: failed to select a version for `chrono`.```

There's a conflict between typedb-driver v2.28.4 asking for chrono =0.4.38 and typeql v2.28.1 asking for chrono =0.4.23.

**Comment by dmitrii-ubskii** [comment]
Looks like we went a little overeager with pinnning dependency versions. Should be fixed by https://github.com/vaticle/dependencies/pull/548 in future releases.
